const API_URL='REPLACE_WITH_GOOGLE_APPS_SCRIPT_WEB_APP_URL';
const $=s=>document.querySelector(s);
const token=new URLSearchParams(location.search).get('c');
const statusEl=$('#status'),bookingEl=$('#booking'),slotsEl=$('#slots'),clientEl=$('#client'),successEl=$('#success');
let client=null;
function setStatus(text,error=false){statusEl.hidden=false;statusEl.textContent=text;statusEl.dataset.error=error?'1':'0'}
function groupByDate(slots){return slots.reduce((a,s)=>((a[s.date]??=[]).push(s),a),{})}
function formatDate(v){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date(v+'T12:00:00'))}
async function api(params){if(API_URL.startsWith('REPLACE_'))throw new Error('API_NOT_CONFIGURED');const url=new URL(API_URL);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const r=await fetch(url.toString(),{redirect:'follow'});if(!r.ok)throw new Error('HTTP_'+r.status);return r.json()}
async function load(){if(!token){setStatus('El enlace de reserva no es válido.',true);return}try{const data=await api({action:'availability',token});if(!data.ok)throw new Error(data.error||'UNKNOWN');client=data.client;clientEl.innerHTML=`<strong>${client.name}</strong><br><span>${client.address||''}${client.city?' · '+client.city:''}</span>`;render(data.slots||[]);statusEl.hidden=true;bookingEl.hidden=false}catch(e){setStatus(e.message==='API_NOT_CONFIGURED'?'La aplicación todavía no está conectada al sistema de reservas.':'No se ha podido cargar la disponibilidad.',true)}}
function render(slots){slotsEl.innerHTML='';const groups=groupByDate(slots);if(!slots.length){slotsEl.innerHTML='<div class="day"><h2>No quedan horas libres</h2><p>Contacta por WhatsApp para buscar otra fecha.</p></div>';return}Object.entries(groups).forEach(([date,items])=>{const box=document.createElement('section');box.className='day';box.innerHTML=`<h2>${formatDate(date)}</h2><div class="slot-grid"></div>`;const grid=box.querySelector('.slot-grid');items.forEach(s=>{const b=document.createElement('button');b.className='slot';b.type='button';b.textContent=s.time;b.onclick=()=>book(s,b);grid.appendChild(b)});slotsEl.appendChild(box)})}
async function book(slot,button){const buttons=[...document.querySelectorAll('.slot')];buttons.forEach(b=>b.disabled=true);button.textContent='Confirmando…';try{const data=await api({action:'book',token,slotId:slot.id});if(!data.ok){if(data.error==='SLOT_TAKEN'){setStatus('Esta hora acaba de ser reservada. Actualizando opciones…',true);await load();return}throw new Error(data.error||'BOOKING_FAILED')}bookingEl.hidden=true;statusEl.hidden=true;successEl.hidden=false;$('#successText').textContent=`${formatDate(data.booking.date)} · ${data.booking.time}`;}catch(e){setStatus('No se ha podido confirmar. Vuelve a intentarlo.',true);buttons.forEach(b=>b.disabled=false);button.textContent=slot.time}}
$('#noneFit').addEventListener('click',()=>{if(!client)return;const phone=(client.whatsapp||'').replace(/\D/g,'');const text=`Hola, soy ${client.name}. No puedo asistir en ninguna de las horas propuestas para el mantenimiento de ${client.address||'mi domicilio'}. ¿Podemos buscar otra fecha?`;location.href=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`});
load();
